[package]
name = "lambda-ec2-regions"
version = "0.1.1"
authors = ["Ian Weller <ianweller@buttslol.net>"]

[lib]
name = "lambda"
crate-type = ["dylib"]

[dependencies]
# Normally you'd write: crowbar = "0.1"
crowbar = { path = "../..", version = "0.1" }
cpython = { version = "*", default-features = false, features = ["python27-sys"] }
rusoto = { version = "0.21", features = ["ec2"] }

[features]
unstable = ["rusoto/unstable"]
