[package]
name = "crowbar"
version = "0.0.1"
authors = ["Ian Weller <ianweller@buttslol.net>"]
description = "Wrapper to simplify writing AWS Lambda functions in Rust (using the Python execution environment)"
repository = "https://github.com/ianweller/rust-crowbar"
keywords = ["aws", "lambda"]
license = "MIT/Apache-2.0"

[dependencies]
serde_json = "0.8"

[dependencies.cpython]
version = "*"
default-features = false
features = ["python27-sys"]

[dependencies.cpython-json]
version = "0.1"
default-features = false
features = ["python27-sys"]
