[package]
name = "lambda-echo"
version = "0.2.0"
authors = ["Iliana Weller <ilianaw@buttslol.net>"]

[lib]
name = "lambda"
crate-type = ["cdylib"]

[dependencies]
# Normally you'd write: crowbar = "0.2"
crowbar = { path = "../..", version = "0.2" }
cpython = "0.1"
